//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDeneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class concert_details
    {
        public long event_id { get; set; }
        public Nullable<int> duration_min { get; set; }
        public string headliner { get; set; }
        public string opener { get; set; }
        public Nullable<long> music_genre_main_id { get; set; }
    
        public virtual events events { get; set; }
    }
}
